name: Deploy Staging to Firebase Hosting

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 12
          cache: yarn

      - name: Install Firebase Tools
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:release:staging

      - name: Deploy
        if:  github.event_name != 'pull_request' || (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: yarn deploy:firebase:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload deploy error logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: firebase-debug.log
          path: firebase-debug.log
