name: Deploy Staging to Firebase Hosting

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Firebase Tools
        run: yarn global add firebase-tools

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:release:staging

      - name: Deploy
        if:  github.event_name != 'pull_request' || (github.event.action == 'closed' && github.event.pull_request.merged == true)
        run: yarn deploy:firebase:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


